server:
  port: 8090

chatbot-api:
  groupId: 28885518425541
  cookie: sensorsdata2015jssdkcross={"distinct_id":"185aea720987e3-03e3d62419909c4-26021151-1327104-185aea72099204","first_id":"","props":{"$latest_traffic_source_type":"引荐流量","$latest_search_keyword":"未取到值","$latest_referrer":"https://www.yuque.com/"},"identities":"eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMTg1YWVhNzIwOTg3ZTMtMDNlM2Q2MjQxOTkwOWM0LTI2MDIxMTUxLTEzMjcxMDQtMTg1YWVhNzIwOTkyMDQifQ==","history_login_id":{"name":"","value":""},"$device_id":"185aea720987e3-03e3d62419909c4-26021151-1327104-185aea72099204"}; zsxq_access_token=BBDFA1D7-9B4A-7B9C-B226-43BC0061AD4D_BE89622F42EF7C54; abtest_env=product; zsxqsessionid=f0153ec262305fb74342d22d1f6aca9e
  openAIKey: ChatGPT上申请的APIkeys